config/routes.rb
Rails.application.routes.draw do
  get "/games", to: "games#index"
  resources :tournaments

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tournaments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
  
  # Adjust default sort order
  self.implicit_order_column = :created_at
  
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.all
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)
    if @tournament.save
      redirect_to @tournament
    
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def tournament_params
      params.require(:tournament).permit(:name, :format, :game_id, :position, :user_id, :players)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>
<ul>
  <% @games.each do |game| %>
    <li>
      <%= game.name %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TournamentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tournaments/index.html.erb
<h1>Tournaments#index</h1>
<p>Find me in app/views/tournaments/index.html.erb</p>
<% @tournaments.each do |tournament| %>
    <li>
        <%= link_to tournament.id, tournament_path(tournament) %>
    </li>
<% end %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= form_with model: @tournament do |form| %>
  <div>
    <%= form.label :format %><br>
    <%= form.text_field :format %>
    <% @tournament.errors.full_messages_for(:format).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :game %><br />
    <%= form.select :game_id, options_for_select(Game.all.map{|s|[s.name, s.id]}) %>
    <% @tournament.errors.full_messages_for(:game).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :position %><br>
    <%= form.text_area :position %><br>
    <% @tournament.errors.full_messages_for(:position).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :user %><br />
    <%= form.select :user_id, options_for_select(User.all.map{|s|[s.name, s.id]}) %>
    <% @tournament.errors.full_messages_for(:user).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :players %><br>
    <%= form.text_area :players %><br>
    <% @tournament.errors.full_messages_for(:players).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tournaments/show.html.erb
<h1><%= @tournament.format %></h1>

<p><%= @tournament.game_id %></p>
<p><%= @tournament.user_id %></p>
<p><%= @tournament.format %></p>
<p><%= @tournament.players %></p>